mklink /D "C:\Users\phoen\.config" "D:\Users\phoen\dotfiles\.config"
mklink /D "D:\Users\phoen\Documents\PowerShell" "D:\Users\phoen\dotfiles\WindowsPowerShell"
mklink /D "C:\Users\phoen\AppData\Local\Temp" "D:\Users\phoen\AppData\Local\Temp"
mklink /D "D:\Users\phoen\.vscode" "C:\Users\phoen\.vscode"
mklink /D "C:\Users\phoen\AppData\Local\Google\Chrome\User Data" "D:\Users\phoen\AppData\Local\Google\Chrome\User Data"
mklink /D "C:\Users\phoen\AppData\Local\Vivaldi\Application" "D:\Users\phoen\AppData\Local\Vivaldi\Application"
mklink /D "C:\Users\phoen\AppData\Local\Vivaldi\User Data" "D:\Users\phoen\AppData\Local\Vivaldi\User Data"
mklink /D "C:\Users\phoen\AppData\Local\Google\Chrome\Application" "D:\Users\phoen\AppData\Local\Google\Chrome\Application"
mklink "C:\Users\phoen\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json" "D:\Users\phoen\dotfiles\Microsoft.WindowsTerminal\settings.json"
mklink /D "C:\Users\phoen\AppData\Roaming/nushell" "D:\Users\phoen\dotfiles\nushell"
mklink /D "C:\Users\phoen\AppData\Roaming/Code" "D:\Users\phoen\AppData\Roaming\Code"
